<a href="https://colab.research.google.com/github/nrao57/tensorflow_hub/blob/main/BirdsTest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import and Process the Image to Classify

In [ ]:
from PIL import Image
import numpy as np

Import and Process the image

In [ ]:
img = Image.open("/content/bird_images/external-content.duckduckgo.com.jpeg").convert('L').resize((224, 224), Image.ANTIALIAS)
img = np.array(img)
print(img.shape)
# scale the image to [0, 1]
print(img.max())
img_scaled = np.absolute(img) / img.max()
print(img_scaled.max())

(224, 224)
250
1.0


In [ ]:
# Img after scaling
print(img_scaled)

[[0.496 0.492 0.488 ... 0.532 0.524 0.532]
 [0.488 0.484 0.48  ... 0.516 0.508 0.508]
 [0.476 0.472 0.468 ... 0.5   0.492 0.492]
 ...
 [0.416 0.368 0.48  ... 0.68  0.68  0.692]
 [0.428 0.376 0.516 ... 0.684 0.692 0.696]
 [0.436 0.38  0.548 ... 0.692 0.696 0.708]]


# Import Tensorflow Hub Model as keras layer

[Import tensorflow_hub model as keras layer
](https://)




In [ ]:
# TF2 version
import tensorflow.compat.v2 as tf
import tensorflow_hub as hub

m = hub.KerasLayer('https://tfhub.dev/google/aiy/vision/classifier/birds_V1/1')

INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


# Use imported model to make prediction

In [ ]:
m(img_scaled)

InvalidArgumentError: ignored

# Resources

https://medium.com/ymedialabs-innovation/how-to-use-tensorflow-hub-with-code-examples-9100edec29af